### ISSUE TITLE
"hex" vs. "base16"

### ISSUE THREAD

**Issue by domenic** [lucacasonato/proposal-binary-encoding#5]
https://datatracker.ietf.org/doc/html/rfc4648#section-8 defines the encoding as the "Base 16 Encoding" and says

> Essentially, Base 16 encoding is the standard case-insensitive hex encoding and may be referred to as "base16" or "hex".

This proposal calls it "hex" in the API. Should it be "base16" instead? Should both be allowed, similar to how the encoding standard defines multiple labels mapping to a single encoding name? (In which case, we'd still need to pick a canonical name for the getter.)

**Comment by bakkot** [comment]
`hex` is definitely the common name. See [java](https://docs.oracle.com/javase/8/docs/api/java/lang/Long.html#toHexString-long-), [go](https://golang.org/pkg/encoding/hex/), [python](https://docs.python.org/3/library/functions.html#hex), etc. I don't think anyone outside of that RFC commonly calls it "base 16".

**Comment by lucacasonato** [comment]
Did some searching with sourcegraph in in js language code:

123.4k results for `"hex"`: https://sourcegraph.com/search?q=context:global+lang:javascript+%22hex%22+count:all&patternType=literal
73 results for `"base16"`: https://sourcegraph.com/search?q=context:global+lang:javascript+%22base16%22+count:all&patternType=literal

Hex is clearly more used, so I'd say we stick with that.

**Comment by domenic** [comment]
I'd suggest adding a minor FAQ entry to the explainer with that research and also @bakkot's comment, in case others have the same question. (Although given how lopsided the results are, maybe I am the only one with such a question...)

**Comment by lucacasonato** [comment]
Done!
